export const ALL_COLORS = [
  'red',
  'cyan',
  'purple',
  'gold',
  'green',
  'pink',
  'yellow',
  'blue',
];

export const LEVELS = [
  // 1-3: Learn Colors
  {
    level: 1,
    title: 'Morning Breeze',
    mechanic: 'Learn Colors',
    themeMechanics: {
      space: 'COSMIC INTRO',
      beach: 'CALM BREEZE',
      dystopian: 'SYSTEM BOOT',
      slimy: 'OOZE DRIP',
      salman: 'SAFARI TRAIL',
    },
    subtitle: 'Slow drift & large targets',
    targetPopsNeeded: 3,
    speedMultiplier: 0.9,
    balloonCount: 12,
    colors: ['red', 'cyan', 'gold'],
    bonusPoints: 50,
    movementStyle: 'linear',
    balloonScaleMod: 1.15,
  },
  {
    level: 2,
    title: 'Gentle Drift',
    mechanic: 'Color Intro',
    themeMechanics: {
      space: 'ORBIT DRIFT',
      beach: 'TIDE DRIFT',
      dystopian: 'SMOG DRIFT',
      slimy: 'SLIME SLIDE',
      salman: 'DESERT DRIFT',
    },
    subtitle: '4 colors in the sky',
    targetPopsNeeded: 4,
    speedMultiplier: 1.0,
    balloonCount: 13,
    colors: ['red', 'cyan', 'gold', 'purple'],
    bonusPoints: 75,
    movementStyle: 'linear',
    balloonScaleMod: 1.1,
  },
  {
    level: 3,
    title: 'Skyward Pulse',
    mechanic: 'Steady Float',
    themeMechanics: {
      space: 'STAR PULSE',
      beach: 'OCEAN PULSE',
      dystopian: 'SYNTH PULSE',
      slimy: 'GOOP PULSE',
      salman: 'HIGHWAY PULSE',
    },
    subtitle: 'Smooth winds rising',
    targetPopsNeeded: 4,
    speedMultiplier: 1.1,
    balloonCount: 14,
    colors: ['red', 'cyan', 'gold', 'purple', 'green'],
    bonusPoints: 100,
    movementStyle: 'linear',
    balloonScaleMod: 1.05,
  },
  // 4-6: Faster Balloons
  {
    level: 4,
    title: 'Windstream',
    mechanic: 'Faster Balloons',
    themeMechanics: {
      space: 'SOLAR WIND',
      beach: 'COASTAL GUST',
      dystopian: 'TOXIC CURRENT',
      slimy: 'MUDDY CURRENT',
      salman: 'HORSEPOWER GUST',
    },
    subtitle: 'Speed picked up!',
    targetPopsNeeded: 5,
    speedMultiplier: 1.3,
    balloonCount: 15,
    colors: ['red', 'cyan', 'gold', 'purple', 'green', 'pink'],
    bonusPoints: 125,
    movementStyle: 'wave',
    balloonScaleMod: 1.0,
  },
  {
    level: 5,
    title: 'Cloud Mirage',
    mechanic: 'High Gust',
    themeMechanics: {
      space: 'SOLAR FLARE',
      beach: 'TROPICAL SWELL',
      dystopian: 'ACID RAIN',
      slimy: 'RADIOACTIVE GUST',
      salman: 'BHAI’S SWELL',
    },
    subtitle: '7 colors floating briskly',
    targetPopsNeeded: 5,
    speedMultiplier: 1.45,
    balloonCount: 16,
    colors: ['red', 'cyan', 'gold', 'purple', 'green', 'pink', 'yellow'],
    bonusPoints: 150,
    movementStyle: 'wave',
    balloonScaleMod: 0.98,
  },
  {
    level: 6,
    title: 'Neon Twilight',
    mechanic: 'Full Spectrum',
    themeMechanics: {
      space: 'ASTEROID DUST',
      beach: 'CORAL SHIMMER',
      dystopian: 'NEON OVERLOAD',
      slimy: 'BIO-HAZARD',
      salman: 'LAND CRUISER RUSH',
    },
    subtitle: 'All 8 colors in flight',
    targetPopsNeeded: 6,
    speedMultiplier: 1.6,
    balloonCount: 16,
    colors: ALL_COLORS,
    bonusPoints: 175,
    movementStyle: 'wave',
    balloonScaleMod: 0.95,
  },
  // 7-9: Smaller Targets
  {
    level: 7,
    title: 'Micro Drift',
    mechanic: 'Smaller Targets',
    themeMechanics: {
      space: 'MICRO GRAVITY',
      beach: 'SAND PINCH',
      dystopian: 'PRECISION LOCK',
      slimy: 'TIGHT SPLATTER',
      salman: 'PRECISION DRIFT',
    },
    subtitle: 'Precision aiming needed',
    targetPopsNeeded: 6,
    speedMultiplier: 1.7,
    balloonCount: 17,
    colors: ALL_COLORS,
    bonusPoints: 200,
    movementStyle: 'zigzag',
    balloonScaleMod: 0.85,
  },
  {
    level: 8,
    title: 'Cyclone Horizon',
    mechanic: 'Zig-Zag Sway',
    themeMechanics: {
      space: 'PULSAR SWAY',
      beach: 'RIPTIDE SWAY',
      dystopian: 'GRID GLITCH',
      slimy: 'MUCK WOBBLE',
      salman: 'DUNES ZIG-ZAG',
    },
    subtitle: 'Wavering wind currents',
    targetPopsNeeded: 7,
    speedMultiplier: 1.8,
    balloonCount: 17,
    colors: ALL_COLORS,
    bonusPoints: 225,
    movementStyle: 'zigzag',
    balloonScaleMod: 0.82,
  },
  {
    level: 9,
    title: 'Gravity Shift',
    mechanic: 'Mini Swarm',
    themeMechanics: {
      space: 'GRAVITY SHIFT',
      beach: 'HIGH TIDE',
      dystopian: 'SURVEILLANCE',
      slimy: 'SLUDGE TIDE',
      salman: 'MIDNIGHT SAFARI',
    },
    subtitle: 'Tight targets with rapid bounce',
    targetPopsNeeded: 7,
    speedMultiplier: 1.95,
    balloonCount: 18,
    colors: ALL_COLORS,
    bonusPoints: 250,
    movementStyle: 'zigzag',
    balloonScaleMod: 0.8,
  },
  // 10-12: Decoy Balloons
  {
    level: 10,
    title: 'Decoy Shimmer',
    mechanic: 'Decoy Clones',
    themeMechanics: {
      space: 'NEBULA CLONES',
      beach: 'MIRAGE WAVES',
      dystopian: 'HOLOGRAM DECOYS',
      slimy: 'MUTANT CLONES',
      salman: 'DESERT MIRAGES',
    },
    subtitle: 'Look closely before shooting!',
    targetPopsNeeded: 8,
    speedMultiplier: 2.1,
    balloonCount: 18,
    colors: ALL_COLORS,
    bonusPoints: 300,
    movementStyle: 'crosswind',
    balloonScaleMod: 0.85,
  },
  {
    level: 11,
    title: 'Stratosphere Drift',
    mechanic: 'Crosswinds',
    themeMechanics: {
      space: 'ION STREAM',
      beach: 'TRADE WINDS',
      dystopian: 'CYBER CROSSWIND',
      slimy: 'TOXIC VAPORS',
      salman: 'DESERT CROSSWIND',
    },
    subtitle: 'Horizontal air currents',
    targetPopsNeeded: 8,
    speedMultiplier: 2.2,
    balloonCount: 19,
    colors: ALL_COLORS,
    bonusPoints: 350,
    movementStyle: 'crosswind',
    balloonScaleMod: 0.82,
  },
  {
    level: 12,
    title: 'Solar Glide',
    mechanic: 'High Altitude',
    themeMechanics: {
      space: 'DEEP ORBIT',
      beach: 'LAGOON RUSH',
      dystopian: 'MEGACITY SKY',
      slimy: 'CAVERN SWARM',
      salman: 'JODHPUR SKYLINE',
    },
    subtitle: 'Dense balloon fields',
    targetPopsNeeded: 9,
    speedMultiplier: 2.3,
    balloonCount: 19,
    colors: ALL_COLORS,
    bonusPoints: 400,
    movementStyle: 'crosswind',
    balloonScaleMod: 0.8,
  },
  // 13-15: Rapid Target Shifts
  {
    level: 13,
    title: 'Cosmic Breeze',
    mechanic: 'Rapid Color Shifts',
    themeMechanics: {
      space: 'WARP CYCLE',
      beach: 'CYCLONE CYCLE',
      dystopian: 'DATA CORRUPTION',
      slimy: 'SPORE SHIFT',
      salman: 'TURBO DRIFT',
    },
    subtitle: 'Targets cycle swiftly',
    targetPopsNeeded: 9,
    speedMultiplier: 2.4,
    balloonCount: 20,
    colors: ALL_COLORS,
    bonusPoints: 450,
    movementStyle: 'wave',
    balloonScaleMod: 0.8,
  },
  {
    level: 14,
    title: 'Starlight Rush',
    mechanic: 'Dual Trajectory',
    themeMechanics: {
      space: 'STAR CLUSTER',
      beach: 'REEF SPLIT',
      dystopian: 'FIREWALL RUSH',
      slimy: 'SLIME GEYSER',
      salman: 'TWILIGHT PURSUIT',
    },
    subtitle: 'Intersecting drift paths',
    targetPopsNeeded: 10,
    speedMultiplier: 2.5,
    balloonCount: 20,
    colors: ALL_COLORS,
    bonusPoints: 500,
    movementStyle: 'bounce',
    balloonScaleMod: 0.78,
  },
  {
    level: 15,
    title: 'Quantum Drift',
    mechanic: 'Surge Waves',
    themeMechanics: {
      space: 'QUANTUM SURGE',
      beach: 'TSUNAMI SURGE',
      dystopian: 'OVERCLOCK SURGE',
      slimy: 'ACID SURGE',
      salman: 'NITRO SURGE',
    },
    subtitle: 'Pulsing acceleration',
    targetPopsNeeded: 10,
    speedMultiplier: 2.6,
    balloonCount: 21,
    colors: ALL_COLORS,
    bonusPoints: 550,
    movementStyle: 'bounce',
    balloonScaleMod: 0.78,
  },
  // 16-18: Time Pressure & Hyper Drift
  {
    level: 16,
    title: 'Nebula Vortex',
    mechanic: 'Hyper Velocity',
    themeMechanics: {
      space: 'HYPER JUMP',
      beach: 'HURRICANE FORCE',
      dystopian: 'HYPER MATRIX',
      slimy: 'SLIME ERUPTION',
      salman: 'HIGHWAY SPRINT',
    },
    subtitle: 'Fast reflex challenge',
    targetPopsNeeded: 11,
    speedMultiplier: 2.7,
    balloonCount: 21,
    colors: ALL_COLORS,
    bonusPoints: 600,
    movementStyle: 'zigzag',
    balloonScaleMod: 0.75,
  },
  {
    level: 17,
    title: 'Hyper Velocity',
    mechanic: 'Turbulent Surge',
    themeMechanics: {
      space: 'EVENT HORIZON',
      beach: 'PIRATE MAELSTROM',
      dystopian: 'NEURAL STORM',
      slimy: 'BIO-MELTDOWN',
      salman: 'DESERT DUST STORM',
    },
    subtitle: 'Unpredictable wind shear',
    targetPopsNeeded: 11,
    speedMultiplier: 2.8,
    balloonCount: 22,
    colors: ALL_COLORS,
    bonusPoints: 650,
    movementStyle: 'crosswind',
    balloonScaleMod: 0.75,
  },
  {
    level: 18,
    title: 'Warp Turbulence',
    mechanic: 'Time Rush',
    themeMechanics: {
      space: 'WARP SPEED',
      beach: 'GALE TEMPEST',
      dystopian: 'SYS OVERRIDE',
      slimy: 'HYPER TOXIC',
      salman: 'SPEED OVERLOAD',
    },
    subtitle: 'Lightning fast floating',
    targetPopsNeeded: 12,
    speedMultiplier: 2.9,
    balloonCount: 22,
    colors: ALL_COLORS,
    bonusPoints: 700,
    movementStyle: 'bounce',
    balloonScaleMod: 0.75,
  },
  // 19: Chaos Round
  {
    level: 19,
    title: 'Apex Chaos',
    mechanic: 'Chaos Round',
    themeMechanics: {
      space: 'SUPERNOVA',
      beach: 'KRAKEN CHAOS',
      dystopian: 'CYBER APOCALYPSE',
      slimy: 'SLUDGEMAGEDDON',
      salman: 'BHAI’S APEX CHAOS',
    },
    subtitle: 'Full chaotic storm!',
    targetPopsNeeded: 13,
    speedMultiplier: 3.1,
    balloonCount: 23,
    colors: ALL_COLORS,
    bonusPoints: 850,
    movementStyle: 'bounce',
    balloonScaleMod: 0.72,
  },
  // 20: Grand Master Boss Wave
  {
    level: 20,
    title: 'Supernova Grandmaster',
    mechanic: 'Final Boss Wave',
    themeMechanics: {
      space: 'BLACK HOLE CORE',
      beach: 'PIRATE KING’S ROAR',
      dystopian: 'AI TITAN REIGN',
      slimy: 'TITAN SLIME OVERLORD',
      salman: 'BLOCKBUSTER TITAN BOSS',
    },
    subtitle: 'The ultimate Float challenge!',
    targetPopsNeeded: 15,
    speedMultiplier: 3.3,
    balloonCount: 24,
    colors: ALL_COLORS,
    bonusPoints: 1200,
    movementStyle: 'bounce',
    balloonScaleMod: 0.7,
  },
];

/**
 * Returns the theme-tailored mechanic badge label for a given level and theme.
 * @param {number|object} levelNumberOrConfig - Level number (1-20) or level configuration object.
 * @param {string} theme - 'space' | 'beach' | 'dystopian' | 'slimy'
 * @returns {string} Theme-specific mechanic name (e.g. 'SOLAR FLARE', 'TROPICAL SWELL', etc.)
 */
export function getLevelMechanic(levelNumberOrConfig, theme = 'space') {
  let config = levelNumberOrConfig;
  if (typeof levelNumberOrConfig === 'number') {
    const idx = Math.min(Math.max(0, levelNumberOrConfig - 1), LEVELS.length - 1);
    config = LEVELS[idx];
  }
  if (!config) return 'STEADY FLOAT';
  if (config.themeMechanics && config.themeMechanics[theme]) {
    return config.themeMechanics[theme];
  }
  return config.mechanic || config.title || 'STEADY FLOAT';
}


